/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/farmesy.theme.ts
 * Command: astryx theme build theme/farmesy.theme.ts
 * Generated: 2026-07-24T15:11:42.893Z
 */

/**
 * farmesy theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { farmesyTheme } from './farmesy';
 *   import './farmesy.css';
 */
export const farmesyTheme = {
  name: 'farmesy',
  __built: true,
  tokens: {
    "--color-background-body": "light-dark(#F7F9F4, #12160D)",
    "--color-background-surface": "light-dark(#FFFFFF, #1B2114)",
    "--color-background-card": "light-dark(#FFFFFF, #1B2114)",
    "--color-background-muted": "light-dark(#F1F5EC, #232B1A)",
    "--color-accent": "light-dark(#294719, #8FB56B)",
    "--color-on-accent": "#FFFFFF",
    "--color-success": "#6B8547",
    "--color-on-success": "#FFFFFF",
    "--color-warning": "#EF8844",
    "--color-warning-muted": "light-dark(#FFF2E8, #3A2415)",
    "--color-on-warning": "#182014",
    "--color-text-primary": "light-dark(#182014, #F1F5EC)",
    "--color-text-secondary": "light-dark(#596452, #AEB8A0)",
    "--color-text-disabled": "light-dark(#ABB2A5, #5B6350)",
    "--color-border": "light-dark(#E4E9DF, #2B3323)",
    "--color-border-emphasized": "light-dark(#CCD6C4, #3B4530)",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px rgba(107, 133, 71, 0.16)",
    "--color-track": "light-dark(#E4E9DF, #2B3323)",
    "--color-background-green": "light-dark(#EBF3E1, #1E2A16)",
    "--color-border-green": "#6B8547",
    "--color-icon-green": "light-dark(#294719, #A8C98A)",
    "--color-text-green": "light-dark(#294719, #A8C98A)",
    "--color-background-yellow": "light-dark(#F7FFD2, #2E3312)",
    "--color-border-yellow": "#6B8547",
    "--color-icon-yellow": "light-dark(#17310F, #E0FF20)",
    "--color-text-yellow": "light-dark(#17310F, #E0FF20)",
    "--radius-inner": "6px",
    "--radius-element": "8px",
    "--radius-container": "12px",
    "--font-family-body": "\"Overused Grotesk\", Inter, \"Helvetica Neue\", Arial, sans-serif",
    "--font-family-heading": "\"Overused Grotesk\", Inter, \"Helvetica Neue\", Arial, sans-serif"
  },

};
