/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/farmesy.theme.ts
 * Command: astryx theme build theme/farmesy.theme.ts
 * Generated: 2026-07-24T13:32:40.386Z
 */

/**
 * farmesy theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { farmesyTheme } from './farmesy';
 *   import './farmesy.css';
 */
export const farmesyTheme = {
  name: 'farmesy',
  __built: true,
  tokens: {
    "--color-background-body": "#F7F9F4",
    "--color-background-surface": "#FFFFFF",
    "--color-background-card": "#FFFFFF",
    "--color-background-muted": "#F1F5EC",
    "--color-accent": "#294719",
    "--color-on-accent": "#FFFFFF",
    "--color-success": "#6B8547",
    "--color-on-success": "#FFFFFF",
    "--color-warning": "#EF8844",
    "--color-warning-muted": "#FFF2E8",
    "--color-on-warning": "#182014",
    "--color-text-primary": "#182014",
    "--color-text-secondary": "#596452",
    "--color-text-disabled": "#ABB2A5",
    "--color-border": "#E4E9DF",
    "--color-border-emphasized": "#CCD6C4",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px rgba(107, 133, 71, 0.16)",
    "--color-track": "#E4E9DF",
    "--color-background-green": "#EBF3E1",
    "--color-border-green": "#6B8547",
    "--color-icon-green": "#294719",
    "--color-text-green": "#294719",
    "--color-background-yellow": "#F7FFD2",
    "--color-border-yellow": "#6B8547",
    "--color-icon-yellow": "#17310F",
    "--color-text-yellow": "#17310F",
    "--radius-inner": "6px",
    "--radius-element": "8px",
    "--radius-container": "12px",
    "--font-family-body": "\"Overused Grotesk\", Inter, \"Helvetica Neue\", Arial, sans-serif",
    "--font-family-heading": "\"Overused Grotesk\", Inter, \"Helvetica Neue\", Arial, sans-serif"
  },

};
