/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/farmesy.theme.ts
 * Command: astryx theme build theme/farmesy.theme.ts
 * Generated: 2026-07-24T13:32:40.386Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const farmesyTheme: DefinedTheme;
